
# iOS CircleCI 2.0 configuration file
#

version: 2
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "10.0.0"

    steps:
      - checkout

      - run:
          name: Clone KitBridge
          command: git clone https://github.com/alfwatt/KitBridge.git ../KitBridge

      - run:
          name: Build CardView (iOS)
          command: xcodebuild -scheme "CardView (iOS)"

      - run:
          name: Build KitBridge (macOS)
          command: xcodebuild -scheme "KitBridge (macOS)"
